!function() {

   let lang = {};

   let idiom = 'gbr';
   let idioms = {};

   // Temporary until there is a better build process
   lang.idioms = idioms;

   lang.set = (new_idiom) => {
      if (!idioms[new_idiom]) return;

      idiom = new_idiom;
      // TODO: update database setting

      if (idioms[idiom] && idioms[idiom].locale) d3.timeFormatDefaultLocale(idioms[idiom].locale);
   }

   lang.options = () => Object.keys(idioms);

   function translate(what) {
      if (!what) return '';
      let obj = idioms[idiom];
      let children = what.split('.');
      while (children.length) {
         let child = children.shift();
         obj = obj && obj[child] || '';
      }
      return obj;
   }

   // fall back to English if not found in idiom
   lang.tr = (what) => {
      if (!what) return '';
      if (translate(what)) return translate(what);
      let obj = idioms.gbr;
      let children = what.split('.');
      while (children.length) {
         let child = children.shift();
         obj = obj && obj[child] || '';
      }
      return obj;
   }

   lang.obj = (what) => {
      if (!what) return "";
      if (idioms[idiom] && idioms[idiom][what]) return idioms[idiom][what];
      if (idioms.gbr[what]) return idioms.gbr[what];
      return {};
   }

   idioms.gbr = {
      arp:     'All Ranking Points',
      act:     'Actual',
      rlp:     'Points - Ranking Lists',
      trn:     'Tournament',
      rnd:     'Round',
      dt:      'Date',
      fmt:     'Format',
      cat:     'Category',
      cta:     'Cat.',
      rnk:     'Rank',
      rl:      'Rank List',
      ply:     'Player',
      pyr:     'Players',
      add:     'Add',
      sgi:     'Sign-In',
      sgo:     'Sign-Out',
      scr:     'Score',
      pts:     'Points',
      mts:     'Matches',
      mtc:     'Match',
      drw:     'Draw',
      drz:     'Draws',
      evt:     'Events',
      sch:     'Schedule',
      crt:     'Courts',
      id:      'ID',
      nm:      'Name',
      fnm:     'First Name',
      lnm:     'Last Name',
      bd:      'Birthday',
      yr:      'Year',
      byr:     'Year',
      tot:     'Total',
      sgl:     'Singles',
      dbl:     'Doubles',
      qal:     'Qualifying',
      rrb:     'Round Robin',
      snr:     'Senior',
      unk:     'Unknown',
      dup:     'Duplicate',
      stt:     'Status',
      ord:     'Order',
      clb:     'Club',
      cty:     'City',
      cnt:     'Country',
      kwn:     'Known',
      ioc:     'IOC',
      act:     'Action',
      agd:     'Assigned',
      igr:     'Ignore',
      igd:     'Ignored',
      edt:     'Edit Player',
      sbt:     'Submit',
      ccl:     'Cancel',
      clr:     'Clear',
      und:     'Undo',
      apt:     'Accept',
      dss:     'Dismiss',
      frm:     'From',
      to:      'To',
      h2h:     'Head-to-Head',
      reg:     'Registered',
      gdr:     'Gender',
      dtp:     'Draw Type',
      drp:     'Draw Position',
      adr:     'Automated Draw',
      mdo:     'Draw Order',
      phn:     'Phone',
      email:   'Email',
      asn:     'Association',
      start:   'Start',
      end:     'End',
      ref:     'Referee',
      scoring: 'Scoring',
      time:    'Time',
      duration:'Duration',
      qualifiers: 'Qualifiers',
      none:    'None',
      keys:    'Keys',
      pos:     'Position',
      new:     'New',

      set: 'Settings',
      importexport: 'Import / Export',

      i18n: {
          previousMonth : 'Previous Month',
          nextMonth     : 'Next Month',
          months        : ['January','February','March','April','May','June','July','August','September','October','November','December'],
          weekdays      : ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],
          weekdaysShort : ['Sun','Mon','Tue','Wed','Thu','Fri','Sat']
      },

      settings: {
         general: 'General',
         categories: 'Categories',
         points: 'Points',
         draws: 'Draws',
         data: 'Data',
         publishing: 'Publishing',
      },

      search: {
         players: 'Search Players',
         tournaments: 'Search Tournaments',
         clubs: 'Search Clubs',
         approve: 'Approve Players',
         lastfirst: 'LAST First',
         firstlast: 'First Last',
      },

      formats: {
         singles: 'Singles',
         doubles: 'Doubles',
      },

      draws: {
         feedin: 'Feed-in',
         standard: 'Standard',
         structure: 'Structure',
         brackets: 'Brackets',
         bracketsize: 'Bracket Size',
         roundrobin: 'Round Robin',
         elimination: 'Elimination',
         consolation: 'Consolation',
         qualification: 'Qualification',
         remove: 'Remove',
         changestatus: 'Change Status',
         penalty: 'Assess Penalty',
         umpire: 'Select Referee',
         matchumpire: 'Match Referee',
         matchtime: 'Match Time',
         timeheader: 'Time Heading',
         maindraw: 'Main Draw',
         unscheduled: 'Unscheduled Matches',
         scheduled: 'Scheduled Matches',
         completed: 'Completed',
         unpublished: 'Unpublished',
         publisheduptodate: 'Up to Date',
         publishedoutofdate: 'Out of Date',
         published: 'Published',
         publish: 'Publish',
         publishQ: 'Publish Draw?',
         leaders: 'Leaders',
         playerrep: 'Representative',
         playerreps: 'Representatives',
         luckylosers: 'Lucky Losers (LL)/Replacements',
         lastdirectaccept: 'Last Direct Acceptance',
         clear: 'Clear Draw',
         swap: 'Swap Position',
         alternate: 'Alternate',
         luckyloser: 'Lucky Loser',
      },

      print: {
         schedule: 'Schedule',
         draw: 'Print',
         signin: 'Sign-In Sheet',
         ranklist: 'Rank List',
      },

      tournaments: {
         new: 'New Tournament',
         add: 'Add Tournament',
         edit: 'Edit',
         done: 'Finish',
         removeall: 'Remove All',
         addall: 'Add All',
         key: 'Authorize',
         fetch: 'Download'
      },

      ddlb: {
         singles:  'Singles Tournament Rank:&nbsp;',
         doubles:  'Doubles Tournament Rank:&nbsp;',
         category: 'Tournament Category:&nbsp;',
         draws:    'Select Event:',
      },

      phrases: {
         action: 'Players requiring some action...',
         search: 'Use the search field above to find players, or click player to edit',
         assign: 'Assign this profile by clicking a player below, or ...&nbsp',
         accept: '&nbspall players',
         trnyz:  'Loading Tournaments ...',
         badfile: 'File Not Recognized',
         invalid: 'Invalid file type',
         fileerror: 'Error reading file',
         pointcalc: 'Point calculation requires tournament category and rank',
         drawcreated: 'Draw Created',
         drawactive: 'Active Draw',
         notcreated: 'Not Created',
         importdata: 'Import Data',
         exportdata: 'Export Data',
         importtemplate: 'Import Template',
         draganddrop: 'Drag and Drop files into this zone',
         schedulematches: 'Schedule Matches',
         notconfigured: 'Not Configured',
         cannotsignout: 'Cannot Sign Out',
         cannotchangerank: 'Cannot Change Rank',
         cannotchangewinner: 'Cannot Change Winner',
         matchmustbecomplete: 'Match Must Be Complete!',
         approvedplayer: 'Player Approved for an Event',
         locallycreated: 'Locally Created Tournament',
         noremote: 'No Remote Registrations to Update',
         calculateranking: 'Calculate Ranking Points',
         generateranklist: 'Generate Rank List',
         norankingdata: 'No Ranking Data',
         oop_system: 'Order of Play',
         schedulepublished: 'Publishing Time:',
         timestamp: 'Date/Time: ',
         rankedplayers: 'Ranked Players',
         judgesignature: 'Signature of Head Umpire:',
         nopointcalcs: 'No Point Calculations for given date',
         nomatches: 'No Matches',
         downloadtemplate: 'Download Import Template',
         add2database: 'Add Players, Tournaments, Rankings to Database',
         noconnection: 'No Connection',
         schedulepriority: 'Match Scheduling Priority',
         send: 'Send',
         export: 'Export',
         pointsvalidfrom: 'Points Valid From',
      },

      events: {
         name: 'Name',
         opponents: 'Opponents',
         teams: 'Teams',
         draw_type: 'Draw Type',
         draw_size: 'Draw Size',
         created: 'Created',
         category: 'Category',
         rank: 'Rank',
         surface: 'Surface',
         approved: 'Approved',
         eligible: 'Eligible',
         ineligible: 'Ineligible',
         unavailable: 'Unavailable',
      },

      locations: {
         newlocation: 'New Location',
         abbreviation: 'Abbr.',
         name: 'Name',
         address: 'Address',
         courts: 'Courts',
         identifiers: 'Court IDs',
      },

      genders: {
         male: 'Male',
         female: 'Female',
         mixed: 'Mixed',
      },

      surfaces: {
         clay: 'Clay',
         hard: 'Hard',
         grass: 'Grass',
         carpet: 'Carpet',
      },

      actions: {
         ok: 'OK',
         add_event: 'Add Event',
         save_event: 'Save Event',
         done: 'Done',
         cancel: 'Cancel',
         refresh: 'Refresh',
         delete_event: 'Delete Event',
         add_player: 'Add Player',
         add_location: 'Add Location',
         save_location: 'Save Location',
         delete_location: 'Delete Location',
      },

      signin: {
         tournament_date: 'Start Date',
         organizer: 'Organizer',
         place: 'Location',
         id: 'Tournament ID',
         rank: 'Tournament Rank',
         judge: 'Head Judge',
         doc_name: 'SIGN-IN SHEET',
         doc_subname: ' ',
         signature: 'Signature',
         registered: 'Registered Players',
         notsignedin: 'Not Signed In',
         signedin: 'Signed In',
         withdrawn: 'Withdrawn',
         medical: 'Medical',
         registration: 'Registration',
         medical_issues: 'Medical Expired',
         create_new_player: 'Create New',
         modifyrankings: 'Modify Rankings',
      },

      schedule: {
         allevents: 'All Events',
         allrounds: 'All Rounds',
         allcourts: 'All Courts',
         autoschedule: 'Auto Schedule',
         clearschedule: 'Clear Schedule',
         orderofplay: 'ORDER OF PLAY',
         matchestime: 'Matches => Time', 
         notbefore: 'Not Before',
         followedby: 'Followed By',
         afterrest: 'After Rest',
         tba: 'TBA',
         nextavailable: 'Next Available',
         oncourt: 'On Court',
         warmingup: 'Warming Up',
         suspended: 'Suspended',
         raindelay: 'Rain Delay',
         clear: 'Clear',
      },
      
      refresh: {
         general: 'Refresh',
         registered: 'Updating Registered Players...',
         players: 'Updating Players...',
         calendar: 'Updating Calendar...',
         clubs: 'Updating Cllubs...',
      },

      penalties: {
         fail2signout: 'Failed to Sign Out',
         illegalcoaching: 'Illegal Coaching',
         ballabuse: 'Ball Abuse',
         racquetabuse: 'Racquet Abuse',
         equipmentabuse: 'Equipment Abuse',
         cursing: 'Swearing',
         rudegestures: 'Rude Gestures',
         foullanguage: 'Foul Language',
         timeviolation: 'Time Violation',
         latearrival: 'Late Arrival',
      },

      // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString
      datelocalization: 'en-EN',
   }

   if (typeof define === "function" && define.amd) define(lang); else if (typeof module === "object" && module.exports) module.exports = lang;
   this.lang = lang;
 
}();

   lang.idioms.cro = {
      arp:     'Bodovi za rang listu',
      act:     'Aktualno',
      rlp:     'Bodovi - Rang Lista',
      trn:     'Turnir',
      rnd:     'Kolo',
      dt:      'Datum',
      fmt:     'Format',
      cat:     'Kategorija',
      cta:     'Kat.',
      rnk:     'Rang',
      rl:      'Rang Lista',
      ply:     'Igrač',
      pyr:     'Igrači',
      add:     'Dodaj',
      sgi:     'Prijavi',
      sgo:     'Odjavi',
      scr:     'Rezultat',
      pts:     'Bodovi',
      mts:     'Susreti',
      mtc:     'Susret',
      drw:     'Kostur',
      drz:     'Ždrijebovi',
      evt:     'Događaji',
      sch:     'Raspored',
      crt:     'Igrališta',
      id:      'ID',
      nm:      'Ime',
      fnm:     'Ime',
      lnm:     'Prezime',
      bd:      'Datum rođenja',
      yr:      'Godina',
      byr:     'Godina rođenja',
      tot:     'Ukupno',
      sgl:     'Pojedinačno',
      dbl:     'Parovi',
      qal:     'Kvalifikacije',
      rrb:     'Round Robin',
      snr:     'Senior',
      unk:     'Nepoznato',
      dup:     'Dupliciraj',
      stt:     'Status',
      ord:     'Redoslijed',
      clb:     'Klub',
      cty:     'Grad',
      cnt:     'Država',
      kwn:     'Poznat',
      ioc:     'IOC',
      act:     'Action',
      agd:     'Assigned',
      igr:     'Ignore',
      igd:     'Ignored',
      edt:     'Uredi igrača',
      sbt:     'Potvrdi',
      ccl:     'Odustani',
      clr:     'Očisti',
      und:     'Vrati',
      apt:     'Prihvati',
      dss:     'Odustani',
      frm:     'Od',
      to:      'Do',
      h2h:     'Head-to-Head',
      reg:     'Registriran',
      gdr:     'Spol',
      dtp:     'Tip ždrijeba',
      drp:     'Pozicija kostura',
      adr:     'Automatski ždrijeb',
      mdo:     'Ručni ždrijeb',
      phn:     'Telefon',
      email:   'Email',
      asn:     'Savez',
      start:   'Početak',
      end:     'Kraj',
      ref:     'Sudac',
      scoring: 'Bodovanje',
      time:    'Vrijeme',
      duration:'Trajanje',
      qualifiers: 'Kvalifikacije',
      none:    'Ništa',
      keys:    'Ključevi',
      pos:     'Posicije',
      new:     'Novi',

      set: 'Postavke',
      importexport: 'Import / Export',

      i18n: {
          previousMonth : 'Previous Month',
          nextMonth     : 'Next Month',
          months        : ['siječanj', 'veljača', 'ožujak', 'travanj', 'svibanj', 'lipanj', 'srpanj', 'kolovoz', 'rujan', 'listopad', 'studeni', 'prosinac'],
          weekdays      : ['nedjelja', 'ponedjeljak', 'utorak', 'srijeda', 'četvrtak', 'petak', 'subota'],
          weekdaysShort : ['NED', 'PON', 'UTO', 'SRI', 'ČET', 'PET', 'SUB']
      },

      settings: {
         general: 'Općenito',
         categories: 'Kategorije',
         points: 'Bodovi',
         draws: 'Ždrijebovi',
         data: 'Podaci',
         publishing: 'Objavljivanje',
      },

      search: {
         players: 'Pretraži igrače',
         tournaments: 'Pretraži turnire',
         clubs: 'Pretraži klubove',
         approve: 'Odobri igrače',
         lastfirst: 'PREZIME Ime',
         firstlast: 'Ime Prezime',
      },

      formats: {
         singles: 'Pojedinačno',
         doubles: 'Parovi',
      },

      draws: {
         feedin: 'Feed-in',
         standard: 'Standard',
         structure: 'Struktura',
         brackets: 'Grupa',
         bracketsize: 'Veličina grupe',
         roundrobin: 'Round Robin',
         elimination: 'Eliminacijski',
         consolation: 'Utješni',
         qualification: 'Kvalifikacije',
         remove: 'Ukloni',
         changestatus: 'Promjena statusa',
         penalty: 'Dodjela kazne',
         umpire: 'Odabir suca',
         matchumpire: 'Susret Sudac',
         matchtime: 'Vrijeme susreta',
         timeheader: 'Opcije vremena susreta',
         maindraw: 'Glavni ždrijeb',
         unscheduled: 'Nezakazani susreti',
         scheduled: 'Zakazani susreti',
         completed: 'Završeni susreti',
         unpublished: 'Neobjavljeno',
         publisheduptodate: 'Ažurirano',
         publishedoutofdate: 'Nije ažurirano',
         published: 'Objavljeno',
         publish: 'Objavi',
         publishQ: 'Objavi ždrijeb?',
         leaders: 'Voditelji turnira',
         playerrep: 'Predstavnik',
         playerreps: 'Predstavnici',
         luckylosers: 'Sretni gubitnici (LL)/Zamjenjuje',
         lastdirectaccept: 'Zadnji direktno primljen igrač',
         clear: 'Isprazni Ždrijeb',
         swap: 'Zamljeni posicije',
         alternate: 'Lista čekanja',
         luckyloser: 'Sretni gubitnikd',
      },

      print: {
         schedule: 'Preuzmi',
         draw: 'Preuzmi',
         signin: 'Lista za prijavu',
         ranklist: 'Print Rank List',
      },

      tournaments: {
         new: 'Novi turnir',
         add: 'Dodaj novi turnir',
         edit: 'Uredi',
         done: 'Gotovo',
         removeall: 'Makni sve',
         addall: 'Dodaj sve',
         key: 'Ovlastiti',
         fetch: 'Preuzimanje'
      },

      ddlb: {
         singles:  'Pojedinačni turniri - Rang:&nbsp;',
         doubles:  'Turniri parova - Rang:&nbsp;',
         category: 'Kategorija turnira:&nbsp;',
         draws:    'Odaberi kateogriju:',
      },

      phrases: {
         action: 'Igrači zahtjevaju neku akciju...',
         search: 'Upotrijebite gornje polje za pretraživanje kako biste pronašli igrača ili kliknite na igrača kako bi ga uredili',
         assign: 'Dodijelite ovaj profil klikom na igrača u nastavku ili ...&nbsp',
         accept: '&nbspall igrača',
         trnyz:  'Učitavanje turnira ...',
         badfile: 'Datoteka nije prepoznata',
         invalid: 'Nevažeća vrsta datoteke',
         fileerror: 'Greška prilikom čitanja datoteke',
         pointcalc: 'Izračun bodova zahtjeva rang i kategoriju turnira',
         drawcreated: 'Ždrijeb kreiran',
         drawactive: 'Ždrijeb u tijeku',
         notcreated: 'Nije kreiran',
         importdata: 'Uvezi podatke',
         exportdata: 'Izvezi podatke',
         importtemplate: 'Uvezi predložak',
         draganddrop: 'Dovuci datoteke ovdje',
         schedulematches: 'Rasporediti Susrete',
         notconfigured: 'Nije konfiguriran',
         cannotsignout: 'Nije moguće odjaviti',
         cannotchangerank: 'Ne može promijeniti rang',
         cannotchangewinner: 'Ne može promijeniti pobjednika',
         matchmustbecomplete: 'Utakmica mora biti dovršena!',
         approvedplayer: 'Igrač odobren za događaj',
         locallycreated: 'Lokalno kreiran turnir',
         noremote: 'Nemoguće učitati daljinske registracije',
         calculateranking: 'Izračunaj rang bodove',
         generateranklist: 'Generiraj rang liste',
         norankingdata: 'Nema podataka o rangu',
         oop_system: 'Igra se po sistemu',
         schedulepublished: 'Raspored objavljen u:',
         timestamp: 'Datum/Vrijeme ždrijeba: ',
         rankedplayers: 'Nositelji',
         judgesignature: 'Potpis Vrhovnog suca',
         nopointcalcs: 'Ne postoji izračun bodova za dani datum',
         nomatches: 'Nema susreta',
         downloadtemplate: 'Preuzmite Uvoz predloška',
         add2database: 'Dodaj igrača, turnire, ljestvice u bazu podataka',
         noconnection: 'Nema veze s poslužiteljem',
         schedulepriority: 'Prioritet raspoređivanja utakmica',
         send: 'Poslati',
         export: 'Izvoz',
         pointsvalidfrom: 'Bodovi vrijede od',
      },

      events: {
         name: 'Ime',
         opponents: 'Protivnik',
         teams: 'Timovi',
         draw_type: 'Vrsta kostura',
         draw_size: 'Veličina',
         created: 'Kreiran',
         category: 'Kategorija',
         rank: 'Rang',
         surface: 'Podloga',
         approved: 'Odobreno',
         eligible: 'Ispunjava uvjete',
         ineligible: 'Ne ispunjava uvjete',
         unavailable: 'Nedostupno',
      },

      locations: {
         newlocation: 'Nova lokacija',
         abbreviation: 'Kratica',
         name: 'Ime',
         address: 'Adresa',
         courts: 'Igrališta',
         identifiers: 'IDs igrališta',
      },

      genders: {
         male: 'Muški',
         female: 'Ženski',
         mixed: 'Mix',
      },

      surfaces: {
         clay: 'Zemlja',
         hard: 'Tvrda',
         grass: 'Trava',
         carpet: 'Tepih',
      },

      actions: {
         ok: 'Uredu',
         add_event: 'Dodaj događaj',
         save_event: 'Spremi događaj',
         done: 'Gotovo',
         cancel: 'Odustani',
         refresh: 'Osvježi',
         delete_event: 'Obriši događaj',
         add_player: 'Dodaj novog igrača',
         add_location: 'Dodaj lokaciju',
         save_location: 'Spremi lokaciju',
         delete_location: 'Obriši lokaciju',
      },

      signin: {
         tournament_date: 'Datum početka',
         organizer: 'Organizator',
         place: 'Mjesto',
         id: 'ID turnira',
         rank: 'Rang turnira',
         judge: 'Vrhovni sudac',
         doc_name: 'LISTA PRIJAVLJENIH IGRAČA',
         doc_subname: ' ',
         signature: 'Potpis',
         registered: 'Predstavnici igrača',
         notsignedin: 'Nisu prijavljeni',
         signedin: 'Prijavljeni',
         withdrawn: 'Odjavljeni',
         medical: 'Medicinski',
         registration: 'Registracija',
         medical_issues: 'Istekla liječnička potvrda',
         create_new_player: 'Stvori Novog',
         modifyrankings: 'Promijeni rang',
      },

      misc: {
         registrations: 'Ažuriranje registriranih igrača...',
         approve: 'Odobri',
         remove: 'Ukloni',
         loading: 'Učitavanje igrača...',
         calendar: 'Ažuriranje kalendara...',
         clubs: 'Učitavanje klubova...',
         tournaments: 'Učitavanje turnira...',
         rankorder: 'Promijeni rang',
         refresh: 'Osvježi',
      },

      schedule: {
         allevents: 'Svi Događaji',
         allrounds: 'Sve Runde',
         allcourts: 'Sve Igrališta',
         autoschedule: 'Automatski Raspored',
         clearschedule: 'Isprazni Raspored',
         orderofplay: 'RASPORED IGRANJA',
         matchestime: 'Utakmice => Vrijeme', 
         notbefore: 'Ne prije',
         followedby: 'Nakon čega slijedi',
         afterrest: 'Nakon odmora',
         tba: 'TBA',
         nextavailable: 'Sljedeće dostupno',
         oncourt: 'Na igralištu',
         warmingup: 'Zagrijavanje',
         suspended: 'Suspenzija',
         raindelay: 'Odgoda zbog vremena',
         clear: 'Izbrišite',
      },

      refresh: {
         general: 'Osvježi',
         registered: 'Učitavanje registriranih igrača...',
         players: 'Učitavanje novih igrača...',
         calendar: 'Učitavanje kalendara...',
         clubs: 'Učitavanje klubova...',
      },

      penalties: {
         fail2signout: 'Nije se odjavio-la',
         illegalcoaching: 'Primanje savjeta i treneri',
         ballabuse: 'Zloupotreba lopte',
         racquetabuse: 'Zloupotreba reketa',
         equipmentabuse: 'Zloupotreba opreme',
         cursing: 'Psovanje',
         rudegestures: 'Prostačka gesta',
         foullanguage: 'Prostački izrazi',
         timeviolation: 'Otezanje igre',
         latearrival: 'Kašnjenje na susret',
      },

      datelocalization: 'hr-HR',

   }

   lang.idioms.fra = {
      arp:     'Tous les points de classement',
      act:     'Courant',
      rlp:     'Points - Classement',
      trn:     'Tournoi',
      rnd:     'Tour',
      dt:      'Date',
      fmt:     'Format',
      cat:     'Catégorie',
      cta:     'Cat.',
      rnk:     'Classement',
      rl:      'Liste de classement',
      ply:     'Joueur',
      pyr:     'Joueurs',
      add:     'Ajouter',
      sgi:     'Sign-In',
      sgo:     'Sign-Out',
      scr:     'Score',
      pts:     'Points',
      mts:     'Matches',
      drw:     'Tableau',
      drz:     'Tableaux',
      evt:     'Evenements',
      sch:     'Programmation',
      crt:     'Courts',
      id:      'ID',
      nm:      'Nom',
      fnm:     'Prenom',
      lnm:     'Nom',
      bd:      'Anniversaire',
      yr:      'Annee',
      byr:     'Annee',
      tot:     'Total',
      sgl:     'Simple',
      dbl:     'Double',
      qal:     'Qualification',
      rrb:     'Matche de Groupe',
      snr:     'Senior',
      unk:     'Inconnu',
      dup:     'Dupliquer',
      stt:     'Status',
      ord:     'Ordre',
      clb:     'Club',
      cty:     'Ville',
      cnt:     'Pays',
      kwn:     'Connu',
      ioc:     'IOC',
      act:     'Action',
      agd:     'Assigné',
      igr:     'Ignorer',
      igd:     'Ignore',
      edt:     'Editer un joueur',
      sbt:     'Soumettre',
      ccl:     'Annuler',
      clr:     'Effacer',
      und:     'Annuler',
      apt:     'Accepter',
      dss:     'Congédier',
      frm:     'De',
      to:      'A',
      h2h:     'Face a Face',
      reg:     'Enregistré',
      gdr:     'Genre',
      dtp:     'Type de tableau',
      drp:     'Position dans le tableau',
      adr:     'Tableau Automatise',
      mdo:     'Ordre du Tableau Manuel',

      search: {
         players: 'Chercher des Joueurs',
         tournaments: 'Chercher des Tournois',
         clubs: 'Chercher des Clubs',
      },

      formats: {
         singles: 'Simples',
         doubles: 'Doubles',
      },

      draws: {
         feedin: 'Feed-in',
         standard: 'Standard',
         structure: 'Structure',
         brackets: 'Groupes',
         bracketsize: 'Taille de groupe',
         roundrobin: 'Match de groupes',
         elimination: 'Elimination',
         consolation: 'Consolation',
         qualification: 'Qualification',
         remove: 'Enlever',
      },

      ddlb: {
         singles:  'Tournoi de Classement en Simple:&nbsp;',
         doubles:  'Tournoi de Classement en Double:&nbsp;',
         category: 'Categorie de Tournoi:&nbsp;',
         draws:    'Selectionner L’Eventement:',
      },

      phrases: {
         action: 'Joueurs necessitant des actions...',
         search: 'Utilisez le champ de recherche au-dessus pour trouver des joueurs ou cliquer sur joueur pour editer',
         assign: 'Assigner ce profile en cliquant sur joueur en dessous ...&nbsp',
         accept: '&nbspall players',
         trnyz:  'Tournois en Chargement ...',
         badfile: 'Fichier pas reconnu',
         invalid: 'Fichier Type Invalide',
         fileerror: 'Erreur de Lecture du Fichier',
         pointcalc: 'La calculation des points nécessite une Catégorie de Tournoi et de Classement',
      },

      events: {
         name: 'Nom',
         opponents: 'Adversaire',
         teams: 'Equipe',
         draw_type: 'Type de Tableau',
         draw_size: 'Taille',
         created: 'Cree',
         category: 'Categorie',
         rank: 'Rang ou Classement',
         surface: 'Surface',
         approved: 'Approuve',
         eligible: 'Eligible',
         ineligible: 'Ineligible',
         unavailable: 'Indisponible',
      },

      genders: {
         male: 'Masculin',
         female: 'Feminin',
         mixed: 'Mixe',
      },

      surfaces: {
         clay: 'Terre Battue',
         hard: 'Dur',
         grass: 'Herbe',
         carpet: 'Moquette',
      },

      actions: {
         add_event: 'Ajouter un Evenement',
         save_event: 'Sauver un Evenement',
         done: 'Fait',
         cancel: 'Annule',
         delete_event: 'Effacer L’evenement',
      },

      signin: {
         tournament_date: 'Date de Depart',
         organizer: 'Organisateur',
         place: 'Location',
         id: 'ID du Tournoi',
         rank: 'Rang du Tournoi',
         judge: 'Arbitre',
         doc_name: 'FEUILLE POUR LE SIGN IN',
         doc_subname: ' ',
         signature: 'Signature',
         registered: 'Joueurs Enregistrés',
         notsignedin: 'Non Signé',
         signedin: 'Signe',
         withdrawn: 'Retrait',
      },

      misc: {
         registrations: 'Mise a jour des Joueurs Enregistres...',
         approve: 'Accepter',
         remove: 'Enlever',
         loading: 'Chargement des Joueurs...',
         calendar: 'Mise A Jour du Calendrier...',
         clubs: 'Chargement des Clubs...',
         tournaments: 'Chargement des Tournois...',
         rankorder: 'Ordre des Rangs',
         refresh: 'Actualiser',
      }
   }


   lang.idioms.ger = {
      arp:     'Alle Ranglisten-Punkte',
      act:     'Aktuell',
      rlp:     'Punkte, Ranglisten',
      trn:     'Turnier',
      rnd:     'Runde',
      dt:      'Datum',
      fmt:     'Format',
      cat:     'Kategorie',
      cta:     'Kat.',
      rnk:     'Rang',
      rl:      'Rangliste',
      ply:     'Spieler',
      pyr:     'Spieler',
      add:     'hinzufügen',
      sgi:     'Anmelden',
      sgo:     'Abmelden',
      scr:     'Stand',
      pts:     'Punkte',
      mts:     'Spiele',
      drw:     'Feld',
      drz:     'Felder',
      evt:     'Ereignis',
      sch:     'Tabelle',
      crt:     'Plätze',
      id:      'ID',
      nm:      'Name',
      fnm:     'Vorname.',
      lnm:     'Nachname.',
      bd:      'Geburtsdatum',
      yr:      'Jahr',
      byr:     'Jahr',
      tot:     'Gesamt',
      sgl:     'Einze',
      dbl:     'Doppel',
      qal:     'Qualifizieren',
      rrb:     'Round Robin',
      snr:     'Senior',
      unk:     'Unbekannt',
      dup:     'Duplikat',
      stt:     'Status',
      ord:     'Reihenfolge',
      clb:     'Verein',
      cty:     'Stadt',
      cnt:     'Land',
      knw:     'Bekannt',
      ioc:     'IOC',
      act:     'Aktion',
      agd:     'Zugeordnet',
      ignore:  'ignorieren',
      ignoret: 'ignoriert',
      edt:     'Spieler hinzufügen',
      submit:  'Submit',
      ccl:     'Abbrechen',
      clr:     'Klar',
      und:     'Rückgängig machen',
      apt:     'Akzeptieren',
      dss:     'Entlassen',
      frn:     'Von',
      to:      'an',
      h2h:     'Kopf-an-Kopf',
      reg:     'Registriert',
      gdr:     'Geschlecht',
      dtp:     'Feld Struktur',
      drp:     'Position im Feld',
      adr:     'Automatisches Feld',
      mdo:     'Manuelle Feldreihenfolge',

      search: {
         players: 'Spieler suchen',
         tournaments: 'Turniere suchen',
         clubs: 'Verein suchen',
      },

      formats: {
         singles: 'Einzel',
         doubles: 'Doppel',
      },

      draws: {
         feedin: 'Feed-In',
         standard: 'Standart',
         structure: 'Struktur',
         brackets: 'Klammern',
         bracketsize: 'Größe der Klammern',
         roundrobin: 'Roundrobin',
         elimination: 'K.O. - System',
         consolation: 'Nebenroun',
         qualification: 'Qualifikation',
         remove: 'Entfernen',
      },

      ddlb: {
         singles: 'Einzel - Turnier Rang:&nbsp',
         doubles: 'Doppel - Turnier Rang:&nbsp',
         category: 'Turnierkategorie:&nbsp',
         draws: 'Ereignis/Turnier aussuchen',
      },

      phrases: {
         action: 'Spieler erfordert Aktion',
         search: 'Benutze Suchfeld um Spieler zu finden',
         assign: 'Ordne dieses Profil durch anklicken des Spielers zu, or ...&nbsp',
         accept: '&nbspalle Spieler',
         trnyz: 'lade Turniere...',
         badfile: 'Datei konnte nicht anerkannt werden',
         invalid: 'ungültiger Dateityp',
         fileerror: 'Fehler beim Lesen der Datei',
         pointcalc: 'Punktberechnung fordert Kategorie des Turniers und Rang',
      },

      events: {
         name: 'Name',
         opponents: 'Gegne',
         teams: 'Mannschaften',
         draw_type: 'Typ des Feldes',
         draw_size: 'Größe des Feldes',
         created: 'Erstellt',
         category: 'kategorie',
         rank: 'Rang',
         surface: 'Belag',
         approved: 'Genehmigt',
         eligible: 'Förderfähig',
         ineligible: 'Nicht förderfähig',
         unavailable: 'Nicht verfügbar',
      },

      genders: {
         male: 'Männlich',
         female: 'Weibliche',
         mixed: 'Mixed',
      },

      surfaces: {
         clay: 'Sand',
         hard: 'Hard',
         grass: 'Rasen',
         carpet: 'Teppich',
      },

      actions: {
         add_event: 'Event hinzufügen',
         save_event: 'Event speichern',
         done: 'Fertig',
         cancel: 'Abbrechen',
         delete_event: 'Event löschenA',
      },

      signin: {
         tournament_date: 'Startdatum',
         organizer: 'Veranstalter',
         place: 'Standort',
         id: 'ID des Turniers',
         rank: 'Rang des Turniers',
         judge: 'Schiedsrichter',
         doc_name: 'Sign-In-Blatt',
         doc_subname: ' ',
         signature: 'Unterschrift',
         registered: 'Registrierte Spieler',
         notsignedin: 'Nicht angemeldet',
         signetin: 'Angemeldet',
         withdrawn: 'Abgemeldet',
      },

   }

   lang.idioms.hun = {
      arp:     'Összes Ranglista Pont',
      act:     'Aktuális',
      rlp:     'Pontok - Ranglisták',
      trn:     'Verseny',
      rnd:     'Forduló',
      dt:      'Dátum',
      fmt:     'Formátum',
      cat:     'Kategória',
      cta:     'Kat.',
      rnk:     'Besorolás',
      rl:      'Ranglista',
      ply:     'Játékos',
      pyr:     'Játékosok',
      add:     'Hozzáad',
      sgi:     'Bejelentkezés',
      sgo:     'Kijelentkezés',
      scr:     'Eredmény',
      pts:     'Pontok',
      mts:     'Meccsek',
      drw:     'Tábla',
      drz:     'Táblák',
      evt:     'Események',
      sch:     'Játékrend',
      crt:     'Pályák',
      id:      'Azonosító',
      nm:      'Név',
      fnm:     'Keresztnév',
      lnm:     'Vezetéknév',
      bd:      'Születésnap',
      yr:      'Év',
      byr:     'Év',
      tot:     'Összes',
      sgl:     'Egyéni',
      dbl:     'Páros',
      qal:     'Kvalifikáció',
      rrb:     'Körmérkőzés',
      snr:     'Szenior',
      unk:     'Ismeretlen',
      dup:     'Ismételt Bejegyzés',
      stt:     'Státusz',
      ord:     'Sorrend',
      clb:     'Klub',
      cty:     'Város',
      cnt:     'Ország',
      kwn:     'Ismert',
      ioc:     'IOC',
      act:     'Művelet',
      agd:     'Kijelölt',
      igr:     'Kihagy',
      igd:     'Kihagyott',
      edt:     'Játékos Profil Szerkesztés',
      sbt:     'Elküld',
      ccl:     'Érvénytelenít',
      clr:     'Töröl',
      und:     'Vissza',
      apt:     'Elfogad',
      dss:     'Elutasít',
      frm:     'Tól-',
      to:      'Ig-',
      h2h:     'Fej-fej állás',
      reg:     'Regisztrált',
      gdr:     'Nem',
      dtp:     'Tábla Típus',
      drp:     'Tábla Pozíció',
      adr:     'Automatikus Tábla',
      mdo:     'Manuális Tábla Sorrend',

      search: {
         players: 'Játékos Kereső',
         tournaments: 'Verseny Kereső',
         clubs: 'Klub Kereső',
      },

      formats: {
         singles: 'Egyéni',
         doubles: 'Páros',
      },

      draws: {
         feedin: 'Betölt',
         standard: 'Standard',
         structure: 'Struktúra',
         brackets: 'Ág',
         bracketsize: 'Ág Méret',
         roundrobin: 'Körmérkőzés',
         elimination: 'Kieséses',
         consolation: 'Vígaszág',
         qualification: 'Kvalifikáció',
         remove: 'Eltávolít',
      },

      ddlb: {
         singles:  'Egyéni Verseny Besorolás:&nbsp;',
         doubles:  'Páros Verseny Besorolás:&nbsp;',
         category: 'Verseny Kategória:&nbsp;',
         draws:    'Verseny:',
      },

      phrases: {
         action: 'Versenyzők melyek figyelmet igényelnek …',
         search: 'Játékos kereséshez használd a fenti keresési mezőt, vagy kattints a szerkesztőre',
         assign: 'A profil hozzárendelése az alábbi játékosokra kattintva, vagy ...&nbsp',
         accept: '&nbspösszes játékos',
         trnyz:  'Versenyek betöltése ...',
         badfile: 'Ismeretlen fájl',
         invalid: 'Hibás fájl típus',
         fileerror: 'File olvasás hiba',
         pointcalc: 'Pontszámításhoz versenykategóriát és rangot kell megadni',
      },

      events: {
         name: 'Név',
         opponents: 'Ellenfelek',
         teams: 'Csapatok',
         draw_type: 'Tábla Típus',
         draw_size: 'Méret',
         created: 'Készítette',
         category: 'Kategória',
         rank: 'Besorolás',
         surface: 'Felület',
         approved: 'Jóváhagyva',
         eligible: 'Engedélyezett',
         ineligible: 'Nem engedélyezett',
         unavailable: 'rendelkezésre nem álló',
      },

      genders: {
         male: 'Férfi',
         female: 'Nő',
         mixed: 'Vegyes',
      },

      surfaces: {
         clay: 'Salak',
         hard: 'Kemény',
         grass: 'Füves',
         carpet: 'Szőnyeg',
      },

      actions: {
         add_event: 'Verseny hozzáadása',
         save_event: 'Verseny mentése',
         done: 'Kész',
         cancel: 'Vissza',
         delete_event: 'Verseny törlése',
      },

      signin: {
         tournament_date: 'Kezdő Dátum',
         organizer: 'Szervező',
         place: 'Hely',
         id: 'Verseny Azonosító',
         rank: 'Verseny Besorolás',
         judge: 'Főbíró',
         doc_name: 'JELENTKEZÉSI LAP',
         doc_subname: ' ',
         signature: 'Aláírás',
         registered: 'Regisztrált Versenyzők',
         notsignedin: 'Jelentkezett',
         signedin: 'Nem jelentkezett',
         withdrawn: 'Visszalépett',
      },

      misc: {
         registrations: 'Regisztrált Versenyzők Frissítése…',
         approve: 'Jóváhagy',
         remove: 'Eltávolít',
         loading: 'Versenyzők Betöltése…',
         calendar: 'Naptás Frissítése…',
         clubs: 'Klubbok Betöltése…',
         tournaments: 'Versenyek Betöltése…',
         rankorder: 'Besorolási Sorrend',
         refresh: 'Frissítés',
      }

   }

   lang.idioms.ita = {

      arp:     'Totale punti',
      act:     'Effettivo',
      rlp:     'Punti - Classifica',
      trn:     'Torneo',
      rnd:     'Turno',
      dt:      'Data',
      fmt:     'Tipologia',
      cat:     'Categoria',
      cta:     'Cat.',
      rnk:     'Pos.',
      rl:      'Classifica',
      ply:     'Giocatore',
      pyr:     'Giocatori',
      add:     'Agg.',
      sgi:     'Firma/conferma',
      sgo:     'Cancellazione',
      scr:     'Punteggio',
      pts:     'Punti',
      mts:     'Incontri',
      drw:     'Tabellone',
      drz:     'Tabelloni',
      evt:     'Competizioni',
      sch:     'Orario',
      crt:     'Campi',
      id:      'ID',
      nm:      'Nome',
      fnm:     'Nome',
      lnm:     'Cognome',
      bd:      'Data di nascita',
      yr:      'Anno',
      byr:     'Anno',
      tot:     'Totale',
      sgl:     'Singolare',
      dbl:     'Doppio',
      qal:     'Qualificazione',
      rrb:     'Girone',
      snr:     'Senior',
      unk:     'Sconosciuto',
      dup:     'Duplicato',
      stt:     'Situazione',
      ord:     'Ordine',
      clb:     'Circolo',
      cty:     'Città',
      cnt:     'Paese',
      kwn:     'Conosciuto',
      ioc:     'IOC',
      act:     'Azione',
      agd:     'Assegnato',
      igr:     'Ignora',
      igd:     'Ignorato',
      edt:     'Seleziona giocatore',
      sbt:     'Sottoporre',
      ccl:     'Cancellare',
      clr:     'Annullare',
      und:     'Tornare indietro',
      apt:     'Accettare',
      dss:     'Rifiuta',
      frm:     'Da',
      to:      'A',
      h2h:     'Testa a Testa',
      reg:     'Registrato',
      gdr:     'Genere',
      dtp:     'Tipologia di tabellone',
      drp:     'Posizione in tabellone',
      adr:     'Tabellone automatico',
      mdo:     'Tabellone in ordine mnauale',

      search: {
         players: 'Ricerca Giocatori',
         tournaments: 'Ricerca Torneo',
         clubs: 'Ricerca Circoli',
      },

      formats: {
         singles: 'Singolare',
         doubles: 'Doppio',
      },

      draws: {
         feedin: 'Entrate',
         standard: 'Normale',
         structure: 'Struttura',
         brackets: 'Parentesi',
         bracketsize: 'Dimensione Parentesi',
         roundrobin: 'Girone',
         elimination: 'Eliminazione',
         consolation: 'Consolazione',
         qualification: 'Qualificazione',
         remove: 'Rimuovere',
      },

      ddlb: {
         singles:  'Torneo di Singolare Classifica:&nbsp;',
         doubles:  'Torneo di Doppio Classifica:&nbsp;',
         category: 'Categoria del Torneo',
         draws:    'Seleziona Evento',
      },

      phrases: {
         action: 'Giocatori richiedenti una qualche azione',
         search: 'Utilizzare il campo di ricerca qui sopra per cercare guocatori o cliccare Seleziona giocatore',
         assign: 'Assegnare questo profilo cliccando un guocatore qui sotto o...&nbsp',
         accept: '&nbspall giocatore',
         trnyz:  'Scaricare Tornei...',
         badfile: 'File Not Recognized',
         invalid: 'Tipo di file (documento) non valido',
         fileerror: 'Errore nella lettura del file',
         pointcalc: 'Il calcolo dei punti richiede categoria del torneo e classifica',
      },

      events: {
         name: 'Nome',
         opponents: 'Avversario',
         teams: 'Squadre',
         draw_type: 'Tipologia di Tabellone',
         draw_size: 'Dimensioni (numero di giocatori)',
         created: 'Creato',
         category: 'Categoria',
         rank: 'Classifica',
         surface: 'Superficie',
         approved: 'Approvato',
         eligible: 'Idoneo',
         ineligible: 'Non Idoneo',
         unavailable: 'Non Disponible',
      },

      genders: {
         male: 'Maschio',
         female: 'Femmina',
         mixed: 'Misto',
      },

      surfaces: {
         clay: 'Terra Battuta',
         hard: 'Duro',
         grass: 'Erba',
         carpet: 'Sintetico',
      },

      actions: {
         add_event: 'Aggiungi Evento',
         save_event: 'Salva Evento',
         done: 'Fatto',
         cancel: 'Cancellare',
         delete_event: 'Eliminare Evento',
      },

      signin: {
         tournament_date: 'Data Inizio',
         organizer: 'Organizzatore',
         place: 'Località',
         id: 'ID Torneo',
         rank: 'Classifica torneo',
         judge: 'Giudice Arbitro',
         doc_name: 'Foglio di Firma',
         doc_subname: ' ',
         signature: 'Firma',
         registered: 'Giocatori Iscritti',
         notsignedin: 'Non Confermato',
         signedin: 'Confermato',
         withdrawn: 'Riterato',
      },
   }

lang.idioms.rus = {
      arp:     'Все рейтинговые баллы',
      act:     'Текущие',
      rlp:     'Баллы - Рейтинг-листы',
      trn:     'Турнир',
      rnd:     'Круг',
      dt:      'Дата',
      fmt:     'Формат',
      cat:     'Категория',
      cta:     'Кат.',
      rnk:     'Ранг',
      rl:      'Рейтинг-лист',
      ply:     'Игрок',
      pyr:     'Игроки',
      add:     'Добавить',
      sgi:     'Заявить',
      sgo:     'Снять',
      scr:     'Результат',
      pts:     'Очки',
      mts:     'Матчи',
      drw:     'Сетка',
      drz:     'Сетки',
      evt:     'События',
      sch:     'Расписание',
      crt:     'Корты',
      id:      'Регистрационный номер',
      nm:      'Имя',
      fnm:     'Имя',
      lnm:     'Фамилия',
      bd:      'Дата рождения',
      yr:      'Год',
      byr:     'Год',
      tot:     'Всего',
      sgl:     'Одиночка',
      dbl:     'Пара',
      qal:     'Квалификация',
      rrb:     'Групповой турнир',
      snr:     'Ветераны',
      unk:     'Неизвестно',
      dup:     'Продублировать',
      stt:     'Статус',
      ord:     'Заказ',
      clb:     'Клуб',
      cty:     'Город',
      cnt:     'Страна',
      kwn:     'Известен',
      ioc:     'IOC',
      act:     'Действие',
      agd:     'Назначен',
      igr:     'Игнорировать',
      igd:     'Проигнорирован',
      edt:     'Редактировать игрока',
      sbt:     'Отправить',
      ccl:     'Отменить',
      clr:     'Очистить',
      und:     'Назад',
      apt:     'Принять',
      dss:     'Отклонить',
      frm:     'От кого',
      to:      'Кому',
      h2h:     'Личные встречи',
      reg:     'Зарегистрирован',
      gdr:     'Пол',
      dtp:     'Тип сетки',
      drp:     'Позиция в сетке',
      adr:     'Автоматическая сетка',
      mdo:     'Сетка в ручном режиме',


      search: {
         players: 'Поиск игроков',
         tournaments: 'Поиск турниров',
         clubs: 'Поиск клубов',
      },


      formats: {
         singles: 'Одиночка',
         doubles: 'Пара',
      },


      draws: {
         feedin: 'Ввести',
         standard: 'Стандарт',
         structure: 'Структура',
         brackets: 'Блоки',
         bracketsize: 'Размер блока',
         roundrobin: 'Групповой турнир',
         elimination: 'Навылет',
         consolation: 'Утешительный турнир',
         qualification: 'Квалификация',
         remove: 'Удалить',
      },


      ddlb: {
         singles:  'Одиночка - рейтинг',
         doubles:  'Пара - рейтинг',
         category: 'Категория турнира',
         draws:    'Выберите событие',
      },


      phrases: {
         action: 'Игроки, которые требуют действия:',
         search: 'Используйте форму поиска, чтобы найти игрока, или кликните на имени для редактирования',
         assign: 'Кликните на имени игрока, чтобы присвоить этот профиль',
         accept: 'Все игроки',
         trnyz:  'Турниры загружаются',
         badfile: 'Файл не опознан',
         invalid: 'Некорректный тип файла',
         fileerror: 'Ошибка чтения файла',
         pointcalc: 'Для расчета баллов необходимы категория и рейтинг турнира',
      },


      events: {
         name: 'Имя',
         opponents: 'Противники',
         teams: 'Команды',
         draw_type: 'Тип сетки',
         draw_size: 'Размер сетки',
         created: 'Создан',
         category: 'Категория',
         rank: 'Ранг',
         surface: 'Покрытие',
         approved: 'Одобрен(а)',
         eligible: 'Допущен',
         ineligible: 'Не допущен',
         unavailable: 'Невозможно',
      },


      genders: {
         male: 'Муж.',
         female: 'Жен.',
         mixed: 'Микст',
      },


      surfaces: {
         clay: 'Грунт',
         hard: 'Хард',
         grass: 'Трава',
         carpet: 'Ковер',
      },


      actions: {
         add_event: 'Добавить событие',
         save_event: 'Сохранить событие',
         done: 'Готово',
         cancel: 'Отменить',
         delete_event: 'Удалить событие',
      },


      signin: {
         tournament_date: 'Дата начала',
         organizer: 'Организатор',
         place: 'Место проведения',
         id: 'Регистрационный номер турнира',
         rank: 'Ранг турнира',
         judge: 'Главный судья',
         doc_name: 'Заявочный лист',
         doc_subname: ' ',
         signature: 'Подпись',
         registered: 'Зарегистрированные игроки',
         notsignedin: 'Не заявился',
         signedin: 'Заявился',
         withdrawn: 'Снялся/лась с турнира',
      },


      misc: {
         registrations: 'Список зарегистрированных игроков обновляется...',
         approve: 'Одобрить',
         remove: 'Удалить',
         loading: 'Список игроков загружается...',
         calendar: 'Календарь обновляется...',
         clubs: 'Список клубов загружается...',
         tournaments: 'Список турниров загружается...',
      }
   }

   lang.idioms.svk = {
      arp:     'Všetky body rebríčka',
      act:     'Aktuálne',
      rlp:     'Body - Rebríčky',
      trn:     'Turnaj',
      rnd:     'Kolo',
      dt:      'Dátum',
      fmt:     'Formát',
      cat:     'Kategória',
      cta:     'Kat.',
      rnk:     'Poradie',
      rl:      'Rebrícek',
      ply:     'Hrác',
      pyr:     'Hráci',
      add:     'Pridat',
      sgi:     'Prihlásit',
      sgo:     'Odhlásit',
      scr:     'Skóre',
      pts:     'Body',
      mts:     'Zápasy',
      drw:     'Pavúk',
      drz:     'Pavúky',
      evt:     'Udalosti',
      sch:     'Plán',
      crt:     'Kurty',
      id:      'ID',
      nm:      'Meno',
      fnm:     'Krstné meno',
      lnm:     'Priezvisko',
      bd:      'Dátum narodenia',
      yr:      'Rok',
      byr:     'Rok narodenia',
      tot:     'Spolu',
      sgl:     'Dvojhra',
      dbl:     'Štvorhra',
      qal:     'Kvalifikácia',
      rrb:     'Round Robin',
      snr:     'Seniori',
      unk:     'Neznáme',
      dup:     'Duplicita',
      stt:     'Stav',
      ord:     'Poradie',
      clb:     'Klub',
      cty:     'Mesto',
      cnt:     'Štát',
      kwn:     'Známe',
      ioc:     'IOC',
      act:     'Akcia',
      agd:     'Priradené',
      igr:     'Ignorovat',
      igd:     'Ignorované',
      edt:     'Upravit Player',
      sbt:     'Potvrd',
      ccl:     'Storno',
      clr:     'Vymazat',
      und:     'Vrátit zmeny',
      apt:     'Akceptovat',
      dss:     'Zrušit',
      frm:     'Od',
      to:      'Do',
      h2h:     'Head-to-Head',
      reg:     'Registrované',
      gdr:     'Pohlavie',
      dtp:     'Typ pavúka',
      drp:     'Pozícia v pavúku',
      adr:     'Automatizovaný pavúk',
      mdo:     'Manuálne Poradie v pavúku',

      search: {
         players: 'Hladat hrácov',
         tournaments: 'Hladat turnaje',
         clubs: 'Hladat kluby',
      },

      formats: {
         singles: 'Dvojhry',
         doubles: 'Štvorhry',
      },

      draws: {
         feedin: 'Vyplnit',
         standard: 'Štandard',
         structure: 'Štruktúra',
         brackets: 'Pásma',
         bracketsize: 'Velkost pásma',
         roundrobin: 'Round Robin',
         elimination: 'Vyradovanie',
         consolation: 'Útecha',
         qualification: 'Kvalifikácia',
         remove: 'Odstránit',
      },

      ddlb: {
         singles:  'Rebricek dvojhra:&nbsp;',
         doubles:  'Rebricek štvorhra:&nbsp;',
         category: 'Kategória turnaja:&nbsp;',
         draws:    'Vyber udalost:',
      },

      phrases: {
         action: 'Hráci vyžadujúci ...',
         search: 'Použi textové pole na vrchu na vyhladanie hrácov, alebo vyber hráca na editoavnie',
         assign: 'Prirad tento profil zvolením hráca, alebo ...&nbsp;',
         accept: '&nbspall hráci',
         trnyz:  'Nahrávam turnaje ...',
         badfile: 'Neznámy súbor',
         invalid: 'Neplatný typ súboru',
         fileerror: 'Chyba pri nacítaní súboru',
         pointcalc: 'Výpocet bodov vyžaduje kategóriu turnaja a rebrícek***',
      },

      events: {
         name: 'Názov',
         opponents: 'Súperi',
         teams: 'Družstvá',
         draw_type: 'Typ pavúka',
         draw_size: 'Velkost',
         created: 'Vytvorené',
         category: 'Kategória',
         rank: 'Rebrícek',
         surface: 'Povrch',
         approved: 'Schválené',
         eligible: 'Oprávnení',
         ineligible: 'Neoprávnení',
         unavailable: 'Nedostupný',
      },

      genders: {
         male: 'Muži',
         female: 'Ženy',
         mixed: 'Mix',
      },

      surfaces: {
         clay: 'Antuka',
         hard: 'Hard',
         grass: 'Tráva',
         carpet: 'Koberec',
      },

      actions: {
         add_event: 'Pridat udalost',
         save_event: 'Uložit udalost',
         done: 'Hotovo',
         cancel: 'Storno',
         delete_event: 'Zmazat udalost',
      },

      signin: {
         tournament_date: 'Zaciatok',
         organizer: 'Organizátor',
         place: 'Lokalita',
         id: 'ID turnaja',
         rank: 'Hodnotenie turnaja',
         judge: 'Hlavný rozhodca',
         doc_name: 'PRIHLASOVACÍ FORMULÁR',
         doc_subname: ' ',
         signature: 'Podpis',
         registered: 'Prihlásení hráci',
         notsignedin: 'Neprihlásení',
         signedin: 'Prihlásení',
         withdrawn: 'Odhlásení',
      },

   }
